In [ ]:
!pip install -q gdown

In [ ]:
import os
import gdown
import warnings
warnings.filterwarnings('ignore')

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk

In [ ]:
# DOWNLOADING PROJECT FILES FROM GOOGLE DRIVE

# https://drive.google.com/drive/folders/12EN31kqExYs3JjILrEF__mS1RnYz_0AW?usp=drive_link
folder_url = "https://drive.google.com/drive/folders/12EN31kqExYs3JjILrEF__mS1RnYz_0AW"

gdown.download_folder(
    folder_url,
    quiet=False,
    use_cookies=False
)

print("Project folders created successfully!")

Retrieving folder contents

Retrieving folder 1vBKj_smCn0T9BNdViqo_MPrd5d7R99XG __pycache__
Processing file 1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg config.cpython-312.pyc
Processing file 1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U transformer_utils.cpython-312.pyc
Processing file 1Gi7HEqAfp9cASYheneZS01DUziK08tdT utils.cpython-312.pyc
Retrieving folder 1bXlYAqeavibqP2Q9Cov8UhqeoOZWvFrA data
Retrieving folder 1lF688G5VMjHVsBy268BOJRqIxTKJevmF .ipynb_checkpoints
Processing file 1kFKjOyRl8L21szt2QFowjxuddkZrsr9x Batch.csv
Processing file 1q-wXklXH_J36OsfLW467j8L1LEg_Lyhd Batch.xlsx
Processing file 1pnkekiXMDL0hyk_1FK4vaCJ-7VYKFpVK ModelComparison.csv
Processing file 1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E processed_train.csv
Processing file 1az3p7_oN-FRK-piYs_3WVrv0KCnxK9D7 scaler.pkl
Processing file 1l3OnQ5ziR_I35IoTkDWp0apjaBxzC9Pq tfidf_vectorizer.pkl
Processing file 11vGfDGB4yoEapDTwb6-4YLr7UXUL21sF train.csv
Processing file 1yFNyBkZxFEhJVkPdbmxL6guizt2yaYCX X_test.pkl
Processing file 1PYC9Ju7Z5KsXpw_pSlkY6Xn0iBYZbgsx X_train.pkl
Processing file 14HGURW_d3CAfbYyqmFkTjgT2oASd81wp y_test.pkl
Processing file 1RxvjGXVDQ96_CgxJBxxdgjZKqHd2oQZN y_train.pkl
Retrieving folder 1BMvNI1yqeLVPjHDwlwUyqxgXqd_bG4Ok models
Retrieving folder 1V4Vha1_imfyzrFj6DtO0Svq6aivsBGOT .ipynb_checkpoints
Retrieving folder 1-uauPsy_0YO-975Wq_rTkRvhNM6hSR58 bert
Processing file 160Rua3VDBj0LoF1U46o9rjYAw_bB2pZk config.json
Processing file 1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE model.safetensors
Processing file 10k7rhsO_x_xUnJUewoq3IWuvwmqwA_Sy tokenizer_config.json
Processing file 1iAdFAeTJydUHJ7jwMRTxALuvl2t-iKj_ tokenizer.json
Processing file 1IxrAq18aWSlSeSVbwiK1s-KzgFRMpDpX training_configuration.csv
Retrieving folder 1EKZKc228ud7ImnIu4NcaLdXLwBmW1wHv distilbert
Processing file 1cjIU_pcsD1uwkQ50ZESBlngRSRTMw8xC config.json
Processing file 1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv model.safetensors
Processing file 1gEbjZ-8fx5drVglahWK9CNQ97LrY7Fqz tokenizer_config.json
Processing file 1vN84tTeurrkyOYUJ-W0NoPPCAUqIfSeY tokenizer.json
Processing file 1W7BZY8vyYQ7tY7nCs3YBuuhy8fBB6uVr training_configuration.csv
Processing file 117ezIrJGiMtobOppOPV_wwwfXa8Y041D bert_model.pt
Processing file 1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw distilbert_model.pt
Processing file 1mrJzFWV5LER1HZyRWNSvBMSyhzCSGfbp LinearSVMModel.pkl
Processing file 1ljH96rXKQsUMMapa5CDzuF7WiviO6BsO LogisticRegressionModel.pkl
Processing file 1Bi9U2ZWUkKhYBZT2d1vlEwoib6i6rz7h NaiveBayesModel.pkl
Processing file 11RURo9NV4zDl6VV_VOr0i8yyMBUpiARd RandomForestModel.pkl
Processing file 1n-P8BoUJogYmTA8z0qw8oVpYyu_aX9MU XGBoostModel.pkl
Retrieving folder 1mD2J_fyWIT4I_eCmBMFUV4SiExy4uhii pages
Processing file 1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv 1_Home.py
Processing file 17-wbVlAKXyVMYklE55wDBh-je_6oDSM0 2_EDA_Dashboard.py
Processing file 1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s 3_Model_Comparison.py
Processing file 1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd 4_Content_Analyzer.py
Processing file 1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL 5_Batch_Prediction.py
Processing file 1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2 app.py
Processing file 1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_ config.py
Processing file 1He6-v2SFde_gvNtaKDIMHXl6MHFqcc6k log.txt
Processing file 1Aaw3jT6xwdeCW-j3qPOYQObsMZdEoFTG requirements.txt
Processing file 1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7 transformer_utils.py
Processing file 1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV utils.py

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From (original): https://drive.google.com/uc?id=1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg
From (redirected): https://drive.google.com/uc?id=1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg&confirm=t&uuid=9de90bf8-8d0d-44c5-9b63-ffd7cf0abd25
To: /content/AI_Content_Review/__pycache__/config.cpython-312.pyc
100%|██████████| 1.86k/1.86k [00:00<00:00, 5.65MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U
From (redirected): https://drive.google.com/uc?id=1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U&confirm=t&uuid=88fc0b10-3359-4a5a-87e1-0f0e5ee6cbfc
To: /content/AI_Content_Review/__pycache__/transformer_utils.cpython-312.pyc
100%|██████████| 3.46k/3.46k [00:00<00:00, 12.2MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1Gi7HEqAfp9cASYheneZS01DUziK08tdT
From (redirected): https://drive.google.com/uc?id=1Gi7HEqAfp9cASYheneZS01DUziK08tdT&confirm=t&uuid=f0ba08cf-7265-4fd6-9d12-c6a1474b3c79
To: /content/AI_Content_Review/__pycache__/utils.cpython-312.pyc
100%|██████████| 8.45k/8.45k [00:00<00:00, 6.91MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kFKjOyRl8L21szt2QFowjxuddkZrsr9x
To: /content/AI_Content_Review/data/Batch.csv
100%|██████████| 15.0k/15.0k [00:00<00:00, 26.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1q-wXklXH_J36OsfLW467j8L1LEg_Lyhd
To: /content/AI_Content_Review/data/Batch.xlsx
100%|██████████| 13.8k/13.8k [00:00<00:00, 31.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pnkekiXMDL0hyk_1FK4vaCJ-7VYKFpVK
To: /content/AI_Content_Review/data/ModelComparison.csv
100%|██████████| 618/618 [00:00<00:00, 2.24MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E
From (redirected): https://drive.google.com/uc?id=1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E&confirm=t&uuid=0c919e5d-dac6-4159-aac8-8acc151a5ef4
To: /content/AI_Content_Review/data/processed_train.csv
100%|██████████| 165M/165M [00:02<00:00, 64.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1az3p7_oN-FRK-piYs_3WVrv0KCnxK9D7
To: /content/AI_Content_Review/data/scaler.pkl
100%|██████████| 1.55k/1.55k [00:00<00:00, 4.74MB/s]
Downloading...
From: https://drive.google.com/uc?id=1l3OnQ5ziR_I35IoTkDWp0apjaBxzC9Pq
To: /content/AI_Content_Review/data/tfidf_vectorizer.pkl
100%|██████████| 113k/113k [00:00<00:00, 3.77MB/s]
Downloading...
From: https://drive.google.com/uc?id=11vGfDGB4yoEapDTwb6-4YLr7UXUL21sF
To: /content/AI_Content_Review/data/train.csv
100%|██████████| 68.8M/68.8M [00:01<00:00, 44.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1yFNyBkZxFEhJVkPdbmxL6guizt2yaYCX
To: /content/AI_Content_Review/data/X_test.pkl
100%|██████████| 9.69M/9.69M [00:00<00:00, 54.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1PYC9Ju7Z5KsXpw_pSlkY6Xn0iBYZbgsx
To: /content/AI_Content_Review/data/X_train.pkl
100%|██████████| 38.7M/38.7M [00:00<00:00, 93.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=14HGURW_d3CAfbYyqmFkTjgT2oASd81wp
To: /content/AI_Content_Review/data/y_test.pkl
100%|██████████| 1.79M/1.79M [00:00<00:00, 13.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RxvjGXVDQ96_CgxJBxxdgjZKqHd2oQZN
To: /content/AI_Content_Review/data/y_train.pkl
100%|██████████| 7.15M/7.15M [00:00<00:00, 45.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=160Rua3VDBj0LoF1U46o9rjYAw_bB2pZk
To: /content/AI_Content_Review/models/bert/config.json
100%|██████████| 1.08k/1.08k [00:00<00:00, 3.68MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE
From (redirected): https://drive.google.com/uc?id=1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE&confirm=t&uuid=67d99d84-69ca-4886-9b0f-5a32dc085f2b
To: /content/AI_Content_Review/models/bert/model.safetensors
100%|██████████| 438M/438M [00:04<00:00, 105MB/s]
Downloading...
From: https://drive.google.com/uc?id=10k7rhsO_x_xUnJUewoq3IWuvwmqwA_Sy
To: /content/AI_Content_Review/models/bert/tokenizer_config.json
100%|██████████| 351/351 [00:00<00:00, 1.32MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iAdFAeTJydUHJ7jwMRTxALuvl2t-iKj_
To: /content/AI_Content_Review/models/bert/tokenizer.json
100%|██████████| 712k/712k [00:00<00:00, 6.17MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IxrAq18aWSlSeSVbwiK1s-KzgFRMpDpX
To: /content/AI_Content_Review/models/bert/training_configuration.csv
100%|██████████| 172/172 [00:00<00:00, 461kB/s]
Downloading...
From: https://drive.google.com/uc?id=1cjIU_pcsD1uwkQ50ZESBlngRSRTMw8xC
To: /content/AI_Content_Review/models/distilbert/config.json
100%|██████████| 909/909 [00:00<00:00, 3.17MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv
From (redirected): https://drive.google.com/uc?id=1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv&confirm=t&uuid=1c36df71-62e7-4305-93d2-db50ea3ba43c
To: /content/AI_Content_Review/models/distilbert/model.safetensors
100%|██████████| 268M/268M [00:01<00:00, 147MB/s]
Downloading...
From: https://drive.google.com/uc?id=1gEbjZ-8fx5drVglahWK9CNQ97LrY7Fqz
To: /content/AI_Content_Review/models/distilbert/tokenizer_config.json
100%|██████████| 357/357 [00:00<00:00, 1.55MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vN84tTeurrkyOYUJ-W0NoPPCAUqIfSeY
To: /content/AI_Content_Review/models/distilbert/tokenizer.json
100%|██████████| 711k/711k [00:00<00:00, 6.72MB/s]
Downloading...
From: https://drive.google.com/uc?id=1W7BZY8vyYQ7tY7nCs3YBuuhy8fBB6uVr
To: /content/AI_Content_Review/models/distilbert/training_configuration.csv
100%|██████████| 178/178 [00:00<00:00, 624kB/s]
Downloading...
From (original): https://drive.google.com/uc?id=117ezIrJGiMtobOppOPV_wwwfXa8Y041D
From (redirected): https://drive.google.com/uc?id=117ezIrJGiMtobOppOPV_wwwfXa8Y041D&confirm=t&uuid=63150a1b-de44-4050-b8ea-47b5e2fda4b6
To: /content/AI_Content_Review/models/bert_model.pt
100%|██████████| 438M/438M [00:07<00:00, 55.2MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw
From (redirected): https://drive.google.com/uc?id=1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw&confirm=t&uuid=a30c5fc1-0ffe-4773-8268-e30cdef077bd
To: /content/AI_Content_Review/models/distilbert_model.pt
100%|██████████| 268M/268M [00:02<00:00, 116MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mrJzFWV5LER1HZyRWNSvBMSyhzCSGfbp
To: /content/AI_Content_Review/models/LinearSVMModel.pkl
100%|██████████| 147k/147k [00:00<00:00, 3.63MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ljH96rXKQsUMMapa5CDzuF7WiviO6BsO
To: /content/AI_Content_Review/models/LogisticRegressionModel.pkl
100%|██████████| 148k/148k [00:00<00:00, 3.80MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Bi9U2ZWUkKhYBZT2d1vlEwoib6i6rz7h
To: /content/AI_Content_Review/models/NaiveBayesModel.pkl
100%|██████████| 581k/581k [00:00<00:00, 5.56MB/s]
Downloading...
From: https://drive.google.com/uc?id=11RURo9NV4zDl6VV_VOr0i8yyMBUpiARd
To: /content/AI_Content_Review/models/RandomForestModel.pkl
100%|██████████| 22.1M/22.1M [00:00<00:00, 77.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n-P8BoUJogYmTA8z0qw8oVpYyu_aX9MU
To: /content/AI_Content_Review/models/XGBoostModel.pkl
100%|██████████| 2.42M/2.42M [00:00<00:00, 16.6MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv
From (redirected): https://drive.google.com/uc?id=1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv&confirm=t&uuid=67bdee34-211a-4967-9913-deab67a8c12d
To: /content/AI_Content_Review/pages/1_Home.py
100%|██████████| 2.20k/2.20k [00:00<00:00, 1.07MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=17-wbVlAKXyVMYklE55wDBh-je_6oDSM0
From (redirected): https://drive.google.com/uc?id=17-wbVlAKXyVMYklE55wDBh-je_6oDSM0&confirm=t&uuid=abaede93-1d35-4745-9889-108c71e65b50
To: /content/AI_Content_Review/pages/2_EDA_Dashboard.py
100%|██████████| 11.2k/11.2k [00:00<00:00, 15.8MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s
From (redirected): https://drive.google.com/uc?id=1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s&confirm=t&uuid=5ec30bad-10c9-44fa-ad56-1d8696bdfb83
To: /content/AI_Content_Review/pages/3_Model_Comparison.py
100%|██████████| 2.44k/2.44k [00:00<00:00, 5.82MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd
From (redirected): https://drive.google.com/uc?id=1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd&confirm=t&uuid=8d7f389f-eeac-40b0-9bca-25de0f3d8b76
To: /content/AI_Content_Review/pages/4_Content_Analyzer.py
100%|██████████| 3.16k/3.16k [00:00<00:00, 8.77MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL
From (redirected): https://drive.google.com/uc?id=1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL&confirm=t&uuid=7c8df1b8-9a1d-4bfa-995c-ed01e1103d8e
To: /content/AI_Content_Review/pages/5_Batch_Prediction.py
100%|██████████| 4.89k/4.89k [00:00<00:00, 8.97MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2
From (redirected): https://drive.google.com/uc?id=1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2&confirm=t&uuid=c3e50828-a7e1-4c0d-85b1-5f2e321fdabd
To: /content/AI_Content_Review/app.py
100%|██████████| 481/481 [00:00<00:00, 1.37MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_
From (redirected): https://drive.google.com/uc?id=1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_&confirm=t&uuid=ea34817d-b97a-48cd-98e0-7b0f914cd1fd
To: /content/AI_Content_Review/config.py
100%|██████████| 1.31k/1.31k [00:00<00:00, 5.33MB/s]
Downloading...
From: https://drive.google.com/uc?id=1He6-v2SFde_gvNtaKDIMHXl6MHFqcc6k
To: /content/AI_Content_Review/log.txt
100%|██████████| 16.9k/16.9k [00:00<00:00, 30.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Aaw3jT6xwdeCW-j3qPOYQObsMZdEoFTG
To: /content/AI_Content_Review/requirements.txt
100%|██████████| 111/111 [00:00<00:00, 432kB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7
From (redirected): https://drive.google.com/uc?id=1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7&confirm=t&uuid=3fa3f4b6-3174-46ab-ad41-d972db90b345
To: /content/AI_Content_Review/transformer_utils.py
100%|██████████| 2.71k/2.71k [00:00<00:00, 9.85MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV
From (redirected): https://drive.google.com/uc?id=1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV&confirm=t&uuid=ca201069-77b4-4a0f-9c15-cd862c2588db
To: /content/AI_Content_Review/utils.py
100%|██████████| 7.71k/7.71k [00:00<00:00, 22.8MB/s]

Project folders created successfully!

Download completed

In [ ]:
PROJECT_DIR = "/content/AI_Content_Review"

In [ ]:
df = pd.read_csv(f"{PROJECT_DIR}/data/processed_train.csv")

In [ ]:
print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 159571
Columns : 22

In [ ]:
df.dropna(inplace=True)

In [ ]:
print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 159504
Columns : 22

In [ ]:
# Target Label Distribution
labels = [
    'toxic',
    'severe_toxic',
    'obscene',
    'threat',
    'insult',
    'identity_hate'
]

df[labels].sum().sort_values(ascending=False)

toxic            15294
obscene           8449
insult            7877
severe_toxic      1595
identity_hate     1405
threat             478
dtype: int64

In [ ]:
# Engineered Features Dataset
engineered_features = [
    'char_count',
    'word_count',
    'sentence_count',
    'avg_word_length',
    'stopword_count',
    'punctuation_count',
    'uppercase_ratio',
    'digit_count',
    'url_count',
    'exclamation_count',
    'question_count'
]

df[engineered_features].head()

,char_count,word_count,sentence_count,avg_word_length,stopword_count,punctuation_count,uppercase_ratio,digit_count,url_count,exclamation_count,question_count
0,171,26,1,5.615385,0,0,0.0,0,0,0,0
1,71,11,1,5.545455,0,0,0.0,0,0,0,0
2,144,22,1,5.590909,0,0,0.0,0,0,0,0
3,368,49,1,6.530612,0,0,0.0,0,0,0,0
4,35,6,1,5.000000,0,0,0.0,0,0,0,0

#**TF-IDF Feature Extraction**

It gives more importance to informative words while reducing the influence of common words.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# Build TF-IDF Features

tfidf = TfidfVectorizer(
    # max_features=10000,
    max_features=3000,
    min_df=5,
    max_df=0.90,
    ngram_range=(1,2)
)

X_tfidf = tfidf.fit_transform(df['clean_text'])

In [ ]:
# Shape
print(X_tfidf.shape)

(159504, 3000)

In [ ]:
# Top TF-IDF Features
feature_names = tfidf.get_feature_names_out()

print(feature_names[:100])

['ability' 'able' 'absolute' 'absolutely' 'absurd' 'abuse' 'abusing'
 'abusive' 'academic' 'accept' 'acceptable' 'accepted' 'accepted notable'
 'access' 'according' 'account' 'accuracy' 'accurate' 'accusation'
 'accuse' 'accused' 'accusing' 'acknowledge' 'across' 'act' 'acting'
 'action' 'active' 'activity' 'actor' 'actual' 'actually' 'ad' 'adam'
 'add' 'add information' 'add top' 'added' 'added article' 'added talk'
 'adding' 'adding note' 'adding top' 'addition' 'additional'
 'additionally' 'address' 'addressed' 'admin' 'administration'
 'administrative' 'administrator' 'admins' 'admit' 'adult' 'advance'
 'advertising' 'advice' 'advise' 'advocate' 'afd' 'affair' 'afraid'
 'africa' 'african' 'age' 'agenda' 'agent' 'ago' 'agree' 'agreed'
 'agreement' 'ah' 'ahead' 'aid' 'aim' 'aint' 'air' 'aircraft' 'aka' 'al'
 'albanian' 'album' 'allegation' 'alleged' 'allow' 'allowed' 'allows'
 'almost' 'alone' 'along' 'already' 'also' 'also please' 'altered'
 'alternative' 'although' 'always' 'amazing' 'america']

In [ ]:
# Function to Save file
import joblib

def save_joblib(obj, file_path):
    # Delete existing file
    if os.path.exists(file_path):
        os.remove(file_path)
        print(f"Deleted: {file_path}")

    # Save new file
    joblib.dump(obj, file_path)
    print(f"Saved: {file_path}")

In [ ]:
# Save TF-IDF Model
import joblib

# joblib.dump( tfidf, "E:/PGDBA/BCG/Content/tfidf_vectorizer.pkl") # jupyter notebook
#save_joblib( tfidf, "/content/drive/MyDrive/Internship/AI_Content_Review/data/tfidf_vectorizer.pkl") # drive
save_joblib( tfidf, f"{PROJECT_DIR}/data/tfidf_vectorizer.pkl") # Manual upload

Deleted: /content/AI_Content_Review/data/tfidf_vectorizer.pkl
Saved: /content/AI_Content_Review/data/tfidf_vectorizer.pkl

***Numerical Feature Scaling***

In [ ]:

# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()

# X_numeric = scaler.fit_transform(df[engineered_features])

from sklearn.preprocessing import MinMaxScaler  # StandardScaler produces negative values, so switching to MinMaxScalar

scaler = MinMaxScaler()

X_numeric = scaler.fit_transform(df[engineered_features])

# Save Scaler

# joblib.dump( scaler, "E:/PGDBA/BCG/Content/scaler.pkl") # jupyter notebook
# save_joblib( scaler, "/content/drive/MyDrive/Internship/AI_Content_Review/data/scaler.pkl") # drive
save_joblib( scaler, f"{PROJECT_DIR}/data/scaler.pkl") # Manual upload

Deleted: /content/AI_Content_Review/data/scaler.pkl
Saved: /content/AI_Content_Review/data/scaler.pkl

***Combine TF-IDF + Numerical Features***

Traditional ML models often perform better when lexical TF-IDF features are augmented with engineered numerical features.

In [ ]:
from scipy.sparse import hstack

X_final = hstack([
    X_tfidf,
    X_numeric
])

print(X_final.shape)

(159504, 3011)

In [ ]:
X = X_final

In [ ]:
y = df[labels]

In [ ]:
!pip install iterative-stratification

Collecting iterative-stratification
  Downloading iterative_stratification-0.1.9-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (3.6.0)
Downloading iterative_stratification-0.1.9-py3-none-any.whl (8.5 kB)
Installing collected packages: iterative-stratification
Successfully installed iterative-stratification-0.1.9

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    multilabel_confusion_matrix,
    hamming_loss,
    jaccard_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

#**Train/Test Split**

***Multi-label Stratified Split***

In [ ]:
# # Multi-label Classification
# not using Binary Classification as there are multiple lables(Toxic, Severe Toxic, Threat, Offensive, Insult, Hate) not just Safe Vs Unsafe

msss = MultilabelStratifiedShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

# Convert COO → CSR
X = X.tocsr()

for train_idx, test_idx in msss.split(X_final, y):

    X_train = X[train_idx]
    X_test = X[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

In [ ]:
# Verify Split

print("="*60)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

print("="*60)

============================================================
Training Features : (127603, 3011)
Testing Features  : (31901, 3011)

Training Labels : (127603, 6)
Testing Labels  : (31901, 6)
============================================================

In [ ]:
# Save Prepared Data

joblib.dump( X_train, f"{PROJECT_DIR}/data/X_train.pkl")
joblib.dump( X_test, f"{PROJECT_DIR}/data/X_test.pkl")
joblib.dump( y_train, f"{PROJECT_DIR}/data/y_train.pkl")
joblib.dump( y_test, f"{PROJECT_DIR}/data/y_test.pkl")

['/content/AI_Content_Review/data/y_test.pkl']

***Key Insights***
1. Text has been transformed into structured numerical representations suitable for machine learning.
2. Engineered features such as word count and punctuation complement TF-IDF by capturing stylistic aspects of comments.
3. TF-IDF preserves the importance of informative terms while reducing the influence of very common words.
4. Combining lexical and numerical features provides a richer representation that can improve model performance for traditional classifiers.
5. The resulting feature matrix is ready for model training and evaluation.

#**Function to Save results to Excel**

In [ ]:
import os
import pandas as pd

# ==========================================================
# RESULT FILE LOCATION
# ==========================================================

RESULT_FOLDER = f"{PROJECT_DIR}/data"
RESULT_FILE = f"{PROJECT_DIR}/data/ModelComparison.csv"  #os.path.join(RESULT_FOLDER, "ModelComparison.csv")

os.makedirs(RESULT_FOLDER, exist_ok=True)

# ==========================================================
# FUNCTION TO SAVE / UPDATE RESULTS
# ==========================================================

def update_results_to_csv(metrics):

    # ------------------------------------------------------
    # First execution -> Create Excel automatically
    # ------------------------------------------------------

    if not os.path.exists(RESULT_FILE):

        model_results = pd.DataFrame([metrics])

    else:

        model_results = pd.read_csv(RESULT_FILE)

        # Remove previous result of the same model
        if "Model" in model_results.columns:
            model_results = model_results[
                model_results["Model"] != metrics["Model"]
            ]

        # Remove Rank column (it will be recreated)
        if "Rank" in model_results.columns:
            model_results = model_results.drop(columns=["Rank"])

        # Append new result
        model_results = pd.concat(
            [model_results, pd.DataFrame([metrics])],
            ignore_index=True
        )

    # ------------------------------------------------------
    # Sort by performance
    # ------------------------------------------------------

    model_results = model_results.sort_values(
        by=["Micro F1", "Macro F1", "Accuracy"],
        ascending=[False, False, False]
    ).reset_index(drop=True)

    # ------------------------------------------------------
    # Create Rank
    # ------------------------------------------------------

    model_results.insert(0, "Rank", range(1, len(model_results) + 1))

    # Move Rank column to first position
    cols = ["Rank"] + [
        c for c in model_results.columns
        if c != "Rank"
    ]

    model_results = model_results[cols]

    # ------------------------------------------------------
    # Round numeric values
    # ------------------------------------------------------

    numeric_cols = model_results.select_dtypes(
        include="number"
    ).columns

    model_results[numeric_cols] = (
        model_results[numeric_cols]
        .round(4)
    )

    # ------------------------------------------------------
    # Save Excel
    # ------------------------------------------------------

    model_results.to_csv(RESULT_FILE, index=False)

    print("=" * 60)
    print(f"{metrics['Model']} results saved successfully.")
    print(f"Results File : {RESULT_FILE}")
    print("=" * 60)

    return model_results

#**Evaluation Function**

In [ ]:
results = []

def evaluate_model(
    model_name,
    y_true,
    y_pred,
    y_prob=None
):

    metrics = {

        "Model":model_name,

        "Accuracy":
        accuracy_score(y_true,y_pred),

        "Micro Precision":
        precision_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Micro Recall":
        recall_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Micro F1":
        f1_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Macro F1":
        f1_score(
            y_true,
            y_pred,
            average='macro',
            zero_division=0
        ),

        "Weighted F1":
        f1_score(
            y_true,
            y_pred,
            average='weighted',
            zero_division=0
        ),

        "Hamming Loss":
        hamming_loss(
            y_true,
            y_pred
        ),

        "Jaccard Score":
        jaccard_score(
            y_true,
            y_pred,
            average='samples',
            zero_division=0
        )
    }

    if y_prob is not None:
        metrics["ROC-AUC"] = roc_auc_score(
            y_true,
            y_prob,
            average="micro"
        )
    else:
        metrics["ROC-AUC"] = np.nan

    results.append(metrics)

    update_results_to_csv(metrics)

    print("="*70)
    print(model_name)
    print("="*70)

    for k,v in metrics.items():

        if k!="Model":

            print(f"{k:<20}: {v:.4f}")

#**Model 1: Logistic Regression**

In [ ]:
lr = OneVsRestClassifier(
    LogisticRegression(
        max_iter=1000,
        random_state=42
    )
)

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

evaluate_model(
    "Logistic Regression",
    y_test,
    pred_lr
)

# save_joblib( lr, "/content/drive/MyDrive/Internship/AI_Content_Review/models/LogisticRegressionModel.pkl") # drive
save_joblib( lr, f"{PROJECT_DIR}/models/LogisticRegressionModel.pkl")

============================================================
Logistic Regression results saved successfully.
Results File : /content/AI_Content_Review/data/ModelComparison.csv
============================================================
======================================================================
Logistic Regression
======================================================================
Accuracy            : 0.9201
Micro Precision     : 0.8594
Micro Recall        : 0.5748
Micro F1            : 0.6889
Macro F1            : 0.5128
Weighted F1         : 0.6811
Hamming Loss        : 0.0190
Jaccard Score       : 0.0456
ROC-AUC             : nan
Deleted: /content/AI_Content_Review/models/LogisticRegressionModel.pkl
Saved: /content/AI_Content_Review/models/LogisticRegressionModel.pkl

#**Model 2: Multinomial Naïve Bayes**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb = OneVsRestClassifier(
    MultinomialNB()
)

nb.fit(X_train, y_train)

pred_nb = nb.predict(X_test)

evaluate_model(
    "Naive Bayes",
    y_test,
    pred_nb
)

# save_joblib(nb, "/content/drive/MyDrive/Internship/AI_Content_Review/models/NaiveBayesModel.pkl")
save_joblib(nb, f"{PROJECT_DIR}/models/NaiveBayesModel.pkl")

============================================================
Naive Bayes results saved successfully.
Results File : /content/AI_Content_Review/data/ModelComparison.csv
============================================================
======================================================================
Naive Bayes
======================================================================
Accuracy            : 0.9133
Micro Precision     : 0.8469
Micro Recall        : 0.4949
Micro F1            : 0.6247
Macro F1            : 0.4272
Weighted F1         : 0.6183
Hamming Loss        : 0.0218
Jaccard Score       : 0.0364
ROC-AUC             : nan
Deleted: /content/AI_Content_Review/models/NaiveBayesModel.pkl
Saved: /content/AI_Content_Review/models/NaiveBayesModel.pkl

#**Model 3: Linear SVM**

In [ ]:
from sklearn.svm import LinearSVC

svm = OneVsRestClassifier(
    LinearSVC(
        random_state=42
    )
)

svm.fit(X_train, y_train)

pred_svm = svm.predict(X_test)

evaluate_model(
    "Linear SVM",
    y_test,
    pred_svm
)

# save_joblib( svm, "/content/drive/MyDrive/Internship/AI_Content_Review/models/LinearSVMModel.pkl")
save_joblib( svm, f"{PROJECT_DIR}/models/LinearSVMModel.pkl")

============================================================
Linear SVM results saved successfully.
Results File : /content/drive/MyDrive/AI_Content_Review/data/ModelComparison.csv
============================================================
======================================================================
Linear SVM
======================================================================
Accuracy            : 0.9208
Micro Precision     : 0.8479
Micro Recall        : 0.6021
Micro F1            : 0.7042
Macro F1            : 0.5411
Weighted F1         : 0.6966
Hamming Loss        : 0.0186
Jaccard Score       : 0.0478
ROC-AUC             : nan
Deleted: /content/drive/MyDrive/AI_Content_Review/models/LinearSVMModel.pkl
Saved: /content/drive/MyDrive/AI_Content_Review/models/LinearSVMModel.pkl

#**Model 4: Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = MultiOutputClassifier(

    RandomForestClassifier(
        n_estimators=200, # 30
        max_depth=20,
        max_features="sqrt",
        min_samples_split=5,
        min_samples_leaf=5,
        bootstrap=True,
        random_state=42,
        n_jobs=-1
    )
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

evaluate_model(
    "Random Forest",
    y_test,
    pred_rf
)

# save_joblib( rf, "/content/drive/MyDrive/Internship/AI_Content_Review/models/RandomForestModel.pkl")
save_joblib( rf, f"{PROJECT_DIR}/models/RandomForestModel.pkl")

============================================================
Random Forest results saved successfully.
Results File : /content/drive/MyDrive/AI_Content_Review/data/ModelComparison.csv
============================================================
======================================================================
Random Forest
======================================================================
Accuracy            : 0.9014
Micro Precision     : 0.9781
Micro Recall        : 0.1333
Micro F1            : 0.2347
Macro F1            : 0.1258
Weighted F1         : 0.2306
Hamming Loss        : 0.0319
Jaccard Score       : 0.0089
ROC-AUC             : nan
Deleted: /content/drive/MyDrive/AI_Content_Review/models/RandomForestModel.pkl
Saved: /content/drive/MyDrive/AI_Content_Review/models/RandomForestModel.pkl

#**Model 5: XGBoost**

In [ ]:
!pip install -q xgboost

In [ ]:
from xgboost import XGBClassifier

xgb = MultiOutputClassifier(

    XGBClassifier(
        n_estimators=300,
        eval_metric='logloss',
        learning_rate=0.1,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.7,
        tree_method="hist",
        max_bin=128,
        reg_alpha=0.0,
        reg_lambda=1.0,
        n_jobs=-1,
        random_state=42
    )

)

xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)

evaluate_model(
    "XGBoost",
    y_test,
    pred_xgb
)
# save_joblib( xgb, "/content/drive/MyDrive/Internship/AI_Content_Review/models/XGBoostModel.pkl")
save_joblib( xgb, f"{PROJECT_DIR}/models/XGBoostModel.pkl")

============================================================
XGBoost results saved successfully.
Results File : /content/drive/MyDrive/AI_Content_Review/data/ModelComparison.csv
============================================================
======================================================================
XGBoost
======================================================================
Accuracy            : 0.9196
Micro Precision     : 0.8543
Micro Recall        : 0.5678
Micro F1            : 0.6822
Macro F1            : 0.5277
Weighted F1         : 0.6754
Hamming Loss        : 0.0194
Jaccard Score       : 0.0434
ROC-AUC             : nan
Deleted: /content/drive/MyDrive/AI_Content_Review/models/XGBoostModel.pkl
Saved: /content/drive/MyDrive/AI_Content_Review/models/XGBoostModel.pkl

#**Model Comparison**

In [ ]:
# comparison_df = pd.DataFrame(results)

# comparison_df = comparison_df.sort_values(
#     by="Micro F1",
#     ascending=False
# )

# comparison_df

# comparison_df.to_csv(f"{PROJECT_DIR}/data/ModelComparison.csv", index=False) # comparison_results.csv

comparison_df = pd.read_csv(f"{PROJECT_DIR}/data/ModelComparison.csv")

comparison_df

,Rank,Model,Accuracy,Micro Precision,Micro Recall,Micro F1,Macro F1,Weighted F1,Hamming Loss,Jaccard Score,ROC-AUC
0,1,Linear SVM,0.9208,0.8479,0.6021,0.7042,0.5411,0.6966,0.0186,0.0478,NaN
1,2,Logistic Regression,0.9201,0.8594,0.5748,0.6889,0.5128,0.6811,0.0190,0.0456,NaN
2,3,XGBoost,0.9196,0.8543,0.5678,0.6822,0.5277,0.6754,0.0194,0.0434,NaN
3,4,Naive Bayes,0.9133,0.8469,0.4949,0.6247,0.4272,0.6183,0.0218,0.0364,NaN
4,5,Random Forest,0.9014,0.9781,0.1333,0.2347,0.1258,0.2306,0.0319,0.0089,NaN

**Multi-Label Confusion Matrix**

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(
    y_test,
    pred_lr
)

for i, label in enumerate(labels):

    print(label)

    print(mcm[i])

    print()

NameError: name 'y_test' is not defined

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(
    y_test,
    pred_nb
)

for i, label in enumerate(labels):

    print(label)

    print(mcm[i])

    print()

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(
    y_test,
    pred_svm
)

for i, label in enumerate(labels):

    print(label)

    print(mcm[i])

    print()

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(
    y_test,
    pred_rf
)

for i, label in enumerate(labels):

    print(label)

    print(mcm[i])

    print()

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(
    y_test,
    pred_xgb
)

for i, label in enumerate(labels):

    print(label)

    print(mcm[i])

    print()