In [ ]:
!pip install -q gdown

In [ ]:
import os
import gdown
import warnings
warnings.filterwarnings('ignore')

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk

In [ ]:
# DOWNLOADING PROJECT FILES FROM GOOGLE DRIVE

# https://drive.google.com/drive/folders/12EN31kqExYs3JjILrEF__mS1RnYz_0AW?usp=drive_link
folder_url = "https://drive.google.com/drive/folders/12EN31kqExYs3JjILrEF__mS1RnYz_0AW"

gdown.download_folder(
    folder_url,
    quiet=False,
    use_cookies=False
)

print("Project folders created successfully!")

Retrieving folder contents

Retrieving folder 1vBKj_smCn0T9BNdViqo_MPrd5d7R99XG __pycache__
Processing file 1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg config.cpython-312.pyc
Processing file 1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U transformer_utils.cpython-312.pyc
Processing file 1Gi7HEqAfp9cASYheneZS01DUziK08tdT utils.cpython-312.pyc
Retrieving folder 1bXlYAqeavibqP2Q9Cov8UhqeoOZWvFrA data
Retrieving folder 1lF688G5VMjHVsBy268BOJRqIxTKJevmF .ipynb_checkpoints
Processing file 1kFKjOyRl8L21szt2QFowjxuddkZrsr9x Batch.csv
Processing file 1q-wXklXH_J36OsfLW467j8L1LEg_Lyhd Batch.xlsx
Processing file 1pnkekiXMDL0hyk_1FK4vaCJ-7VYKFpVK ModelComparison.csv
Processing file 1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E processed_train.csv
Processing file 1az3p7_oN-FRK-piYs_3WVrv0KCnxK9D7 scaler.pkl
Processing file 1l3OnQ5ziR_I35IoTkDWp0apjaBxzC9Pq tfidf_vectorizer.pkl
Processing file 11vGfDGB4yoEapDTwb6-4YLr7UXUL21sF train.csv
Processing file 1yFNyBkZxFEhJVkPdbmxL6guizt2yaYCX X_test.pkl
Processing file 1PYC9Ju7Z5KsXpw_pSlkY6Xn0iBYZbgsx X_train.pkl
Processing file 14HGURW_d3CAfbYyqmFkTjgT2oASd81wp y_test.pkl
Processing file 1RxvjGXVDQ96_CgxJBxxdgjZKqHd2oQZN y_train.pkl
Retrieving folder 1BMvNI1yqeLVPjHDwlwUyqxgXqd_bG4Ok models
Retrieving folder 1V4Vha1_imfyzrFj6DtO0Svq6aivsBGOT .ipynb_checkpoints
Retrieving folder 1-uauPsy_0YO-975Wq_rTkRvhNM6hSR58 bert
Processing file 160Rua3VDBj0LoF1U46o9rjYAw_bB2pZk config.json
Processing file 1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE model.safetensors
Processing file 10k7rhsO_x_xUnJUewoq3IWuvwmqwA_Sy tokenizer_config.json
Processing file 1iAdFAeTJydUHJ7jwMRTxALuvl2t-iKj_ tokenizer.json
Processing file 1IxrAq18aWSlSeSVbwiK1s-KzgFRMpDpX training_configuration.csv
Retrieving folder 1EKZKc228ud7ImnIu4NcaLdXLwBmW1wHv distilbert
Processing file 1cjIU_pcsD1uwkQ50ZESBlngRSRTMw8xC config.json
Processing file 1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv model.safetensors
Processing file 1gEbjZ-8fx5drVglahWK9CNQ97LrY7Fqz tokenizer_config.json
Processing file 1vN84tTeurrkyOYUJ-W0NoPPCAUqIfSeY tokenizer.json
Processing file 1W7BZY8vyYQ7tY7nCs3YBuuhy8fBB6uVr training_configuration.csv
Processing file 117ezIrJGiMtobOppOPV_wwwfXa8Y041D bert_model.pt
Processing file 1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw distilbert_model.pt
Processing file 1mrJzFWV5LER1HZyRWNSvBMSyhzCSGfbp LinearSVMModel.pkl
Processing file 1ljH96rXKQsUMMapa5CDzuF7WiviO6BsO LogisticRegressionModel.pkl
Processing file 1Bi9U2ZWUkKhYBZT2d1vlEwoib6i6rz7h NaiveBayesModel.pkl
Processing file 11RURo9NV4zDl6VV_VOr0i8yyMBUpiARd RandomForestModel.pkl
Processing file 1n-P8BoUJogYmTA8z0qw8oVpYyu_aX9MU XGBoostModel.pkl
Retrieving folder 1mD2J_fyWIT4I_eCmBMFUV4SiExy4uhii pages
Processing file 1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv 1_Home.py
Processing file 17-wbVlAKXyVMYklE55wDBh-je_6oDSM0 2_EDA_Dashboard.py
Processing file 1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s 3_Model_Comparison.py
Processing file 1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd 4_Content_Analyzer.py
Processing file 1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL 5_Batch_Prediction.py
Processing file 1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2 app.py
Processing file 1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_ config.py
Processing file 1He6-v2SFde_gvNtaKDIMHXl6MHFqcc6k log.txt
Processing file 1Aaw3jT6xwdeCW-j3qPOYQObsMZdEoFTG requirements.txt
Processing file 1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7 transformer_utils.py
Processing file 1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV utils.py

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From (original): https://drive.google.com/uc?id=1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg
From (redirected): https://drive.google.com/uc?id=1-YRWR027t8RmchQAkPCIzxMKYE9gDAdg&confirm=t&uuid=57badf61-92d2-49de-998d-cc52c018b5cd
To: /content/AI_Content_Review/__pycache__/config.cpython-312.pyc
100%|██████████| 1.86k/1.86k [00:00<00:00, 4.92MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U
From (redirected): https://drive.google.com/uc?id=1IlDLDjwBAkcdi0jjRuT-skI1DQq-VR5U&confirm=t&uuid=db0eb3c7-c134-44f8-8070-a190d9bde3bd
To: /content/AI_Content_Review/__pycache__/transformer_utils.cpython-312.pyc
100%|██████████| 3.46k/3.46k [00:00<00:00, 14.3MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1Gi7HEqAfp9cASYheneZS01DUziK08tdT
From (redirected): https://drive.google.com/uc?id=1Gi7HEqAfp9cASYheneZS01DUziK08tdT&confirm=t&uuid=7ab658f2-4bdf-43fb-ae30-d1375f29f308
To: /content/AI_Content_Review/__pycache__/utils.cpython-312.pyc
100%|██████████| 8.45k/8.45k [00:00<00:00, 11.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kFKjOyRl8L21szt2QFowjxuddkZrsr9x
To: /content/AI_Content_Review/data/Batch.csv
100%|██████████| 15.0k/15.0k [00:00<00:00, 36.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1q-wXklXH_J36OsfLW467j8L1LEg_Lyhd
To: /content/AI_Content_Review/data/Batch.xlsx
100%|██████████| 13.8k/13.8k [00:00<00:00, 39.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pnkekiXMDL0hyk_1FK4vaCJ-7VYKFpVK
To: /content/AI_Content_Review/data/ModelComparison.csv
100%|██████████| 618/618 [00:00<00:00, 2.58MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E
From (redirected): https://drive.google.com/uc?id=1vL65T3OIZzhkLmOaSEbIMjsy5iNqj09E&confirm=t&uuid=b15884db-5151-475c-88b7-a6b039da9c10
To: /content/AI_Content_Review/data/processed_train.csv
100%|██████████| 165M/165M [00:00<00:00, 180MB/s]
Downloading...
From: https://drive.google.com/uc?id=1az3p7_oN-FRK-piYs_3WVrv0KCnxK9D7
To: /content/AI_Content_Review/data/scaler.pkl
100%|██████████| 1.55k/1.55k [00:00<00:00, 1.61MB/s]
Downloading...
From: https://drive.google.com/uc?id=1l3OnQ5ziR_I35IoTkDWp0apjaBxzC9Pq
To: /content/AI_Content_Review/data/tfidf_vectorizer.pkl
100%|██████████| 113k/113k [00:00<00:00, 82.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=11vGfDGB4yoEapDTwb6-4YLr7UXUL21sF
To: /content/AI_Content_Review/data/train.csv
100%|██████████| 68.8M/68.8M [00:00<00:00, 153MB/s]
Downloading...
From: https://drive.google.com/uc?id=1yFNyBkZxFEhJVkPdbmxL6guizt2yaYCX
To: /content/AI_Content_Review/data/X_test.pkl
100%|██████████| 9.69M/9.69M [00:00<00:00, 182MB/s]
Downloading...
From: https://drive.google.com/uc?id=1PYC9Ju7Z5KsXpw_pSlkY6Xn0iBYZbgsx
To: /content/AI_Content_Review/data/X_train.pkl
100%|██████████| 38.7M/38.7M [00:00<00:00, 172MB/s]
Downloading...
From: https://drive.google.com/uc?id=14HGURW_d3CAfbYyqmFkTjgT2oASd81wp
To: /content/AI_Content_Review/data/y_test.pkl
100%|██████████| 1.79M/1.79M [00:00<00:00, 127MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RxvjGXVDQ96_CgxJBxxdgjZKqHd2oQZN
To: /content/AI_Content_Review/data/y_train.pkl
100%|██████████| 7.15M/7.15M [00:00<00:00, 34.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=160Rua3VDBj0LoF1U46o9rjYAw_bB2pZk
To: /content/AI_Content_Review/models/bert/config.json
100%|██████████| 1.08k/1.08k [00:00<00:00, 1.42MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE
From (redirected): https://drive.google.com/uc?id=1RX_RJhwe_0DBg2Sqk_lBd78DW1Jws4hE&confirm=t&uuid=0778d348-d6ff-4a92-a145-6f4d067e6191
To: /content/AI_Content_Review/models/bert/model.safetensors
100%|██████████| 438M/438M [00:05<00:00, 85.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=10k7rhsO_x_xUnJUewoq3IWuvwmqwA_Sy
To: /content/AI_Content_Review/models/bert/tokenizer_config.json
100%|██████████| 351/351 [00:00<00:00, 1.65MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iAdFAeTJydUHJ7jwMRTxALuvl2t-iKj_
To: /content/AI_Content_Review/models/bert/tokenizer.json
100%|██████████| 712k/712k [00:00<00:00, 101MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IxrAq18aWSlSeSVbwiK1s-KzgFRMpDpX
To: /content/AI_Content_Review/models/bert/training_configuration.csv
100%|██████████| 172/172 [00:00<00:00, 642kB/s]
Downloading...
From: https://drive.google.com/uc?id=1cjIU_pcsD1uwkQ50ZESBlngRSRTMw8xC
To: /content/AI_Content_Review/models/distilbert/config.json
100%|██████████| 909/909 [00:00<00:00, 3.81MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv
From (redirected): https://drive.google.com/uc?id=1QY0nn_jWD2hw1gRM2HmPq3aAIwbRKsBv&confirm=t&uuid=b9fa0eae-0ee9-42f1-b981-bf70a6c697d2
To: /content/AI_Content_Review/models/distilbert/model.safetensors
100%|██████████| 268M/268M [00:03<00:00, 75.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1gEbjZ-8fx5drVglahWK9CNQ97LrY7Fqz
To: /content/AI_Content_Review/models/distilbert/tokenizer_config.json
100%|██████████| 357/357 [00:00<00:00, 833kB/s]
Downloading...
From: https://drive.google.com/uc?id=1vN84tTeurrkyOYUJ-W0NoPPCAUqIfSeY
To: /content/AI_Content_Review/models/distilbert/tokenizer.json
100%|██████████| 711k/711k [00:00<00:00, 124MB/s]
Downloading...
From: https://drive.google.com/uc?id=1W7BZY8vyYQ7tY7nCs3YBuuhy8fBB6uVr
To: /content/AI_Content_Review/models/distilbert/training_configuration.csv
100%|██████████| 178/178 [00:00<00:00, 835kB/s]
Downloading...
From (original): https://drive.google.com/uc?id=117ezIrJGiMtobOppOPV_wwwfXa8Y041D
From (redirected): https://drive.google.com/uc?id=117ezIrJGiMtobOppOPV_wwwfXa8Y041D&confirm=t&uuid=8f896b2c-4f8f-4bf0-87aa-c2f1f26d77fb
To: /content/AI_Content_Review/models/bert_model.pt
100%|██████████| 438M/438M [00:04<00:00, 94.7MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw
From (redirected): https://drive.google.com/uc?id=1yW-b_XvFQHIo8cBbtaGw22Z2uwQXMuTw&confirm=t&uuid=7f670af8-9c18-4de6-9521-4181b31f467f
To: /content/AI_Content_Review/models/distilbert_model.pt
100%|██████████| 268M/268M [00:01<00:00, 173MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mrJzFWV5LER1HZyRWNSvBMSyhzCSGfbp
To: /content/AI_Content_Review/models/LinearSVMModel.pkl
100%|██████████| 147k/147k [00:00<00:00, 73.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ljH96rXKQsUMMapa5CDzuF7WiviO6BsO
To: /content/AI_Content_Review/models/LogisticRegressionModel.pkl
100%|██████████| 148k/148k [00:00<00:00, 83.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Bi9U2ZWUkKhYBZT2d1vlEwoib6i6rz7h
To: /content/AI_Content_Review/models/NaiveBayesModel.pkl
100%|██████████| 581k/581k [00:00<00:00, 110MB/s]
Downloading...
From: https://drive.google.com/uc?id=11RURo9NV4zDl6VV_VOr0i8yyMBUpiARd
To: /content/AI_Content_Review/models/RandomForestModel.pkl
100%|██████████| 22.1M/22.1M [00:00<00:00, 33.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n-P8BoUJogYmTA8z0qw8oVpYyu_aX9MU
To: /content/AI_Content_Review/models/XGBoostModel.pkl
100%|██████████| 2.42M/2.42M [00:00<00:00, 127MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv
From (redirected): https://drive.google.com/uc?id=1UUmrZP61x_ppvDF-kxzSciHJ2ipMzlzv&confirm=t&uuid=bf10856f-1d54-40c5-ae3f-111cd13c2b24
To: /content/AI_Content_Review/pages/1_Home.py
100%|██████████| 2.20k/2.20k [00:00<00:00, 7.87MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=17-wbVlAKXyVMYklE55wDBh-je_6oDSM0
From (redirected): https://drive.google.com/uc?id=17-wbVlAKXyVMYklE55wDBh-je_6oDSM0&confirm=t&uuid=f07fec8c-e3db-4f3c-908e-366ebe145b4f
To: /content/AI_Content_Review/pages/2_EDA_Dashboard.py
100%|██████████| 11.2k/11.2k [00:00<00:00, 26.5MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s
From (redirected): https://drive.google.com/uc?id=1tMqEPEPIWWyUJNqfcqDEDuTknrX8lC7s&confirm=t&uuid=d84246a3-8b89-4137-9f08-ace480300558
To: /content/AI_Content_Review/pages/3_Model_Comparison.py
100%|██████████| 2.44k/2.44k [00:00<00:00, 10.5MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd
From (redirected): https://drive.google.com/uc?id=1KJH73L1Xc66QWz1eTeYn_dhsqGLXmhkd&confirm=t&uuid=1ad457fc-0f64-4d68-a695-f607f8d8b251
To: /content/AI_Content_Review/pages/4_Content_Analyzer.py
100%|██████████| 3.16k/3.16k [00:00<00:00, 12.5MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL
From (redirected): https://drive.google.com/uc?id=1JwWpisRxfARO_S4ajL5dWxWD6n4xgODL&confirm=t&uuid=987b79c7-6ef3-473d-b24f-f1efc8ec4eb7
To: /content/AI_Content_Review/pages/5_Batch_Prediction.py
100%|██████████| 4.89k/4.89k [00:00<00:00, 15.7MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2
From (redirected): https://drive.google.com/uc?id=1RjQ4Z1oJUeFisL88Mrp2o6o9VUkhVHd2&confirm=t&uuid=f9e16009-4965-487f-8c0e-684440e5643e
To: /content/AI_Content_Review/app.py
100%|██████████| 481/481 [00:00<00:00, 2.36MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_
From (redirected): https://drive.google.com/uc?id=1szq3zpoeYC5XvCry-VJjJoXSjF1WAWA_&confirm=t&uuid=98013103-870d-4289-8461-6fed8c2706a0
To: /content/AI_Content_Review/config.py
100%|██████████| 1.31k/1.31k [00:00<00:00, 5.37MB/s]
Downloading...
From: https://drive.google.com/uc?id=1He6-v2SFde_gvNtaKDIMHXl6MHFqcc6k
To: /content/AI_Content_Review/log.txt
100%|██████████| 16.9k/16.9k [00:00<00:00, 34.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Aaw3jT6xwdeCW-j3qPOYQObsMZdEoFTG
To: /content/AI_Content_Review/requirements.txt
100%|██████████| 111/111 [00:00<00:00, 400kB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7
From (redirected): https://drive.google.com/uc?id=1o3jbiOMGNJtY2nhj_OCFveNHB7td8lT7&confirm=t&uuid=a5e2a815-bda9-45c9-ba6d-76efd6699e68
To: /content/AI_Content_Review/transformer_utils.py
100%|██████████| 2.71k/2.71k [00:00<00:00, 3.39MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV
From (redirected): https://drive.google.com/uc?id=1FWudJu2zCJBaJNfT59HGmIO-ZW29v8dV&confirm=t&uuid=4da19bab-cfc7-4c37-88a2-ee30f8952d09
To: /content/AI_Content_Review/utils.py
100%|██████████| 7.71k/7.71k [00:00<00:00, 23.6MB/s]

Project folders created successfully!

Download completed

In [ ]:
PROJECT_DIR = "/content/AI_Content_Review"

In [ ]:
df = pd.read_csv(f"{PROJECT_DIR}/data/processed_train.csv")

In [ ]:
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,label_count,tokens,...,word_count,sentence_count,avg_word_length,stopword_count,punctuation_count,uppercase_ratio,digit_count,url_count,exclamation_count,question_count
0,0000997932d777bf,explanation why the edits made under my userna...,0,0,0,0,0,0,0,"['explanation', 'edits', 'made', 'username', '...",...,26,1,5.615385,0,0,0.0,0,0,0,0
1,000103f0d9cfb60f,daww he matches this background colour im seem...,0,0,0,0,0,0,0,"['daww', 'match', 'background', 'colour', 'im'...",...,11,1,5.545455,0,0,0.0,0,0,0,0
2,000113f07ec002fd,hey man im really not trying to edit war its j...,0,0,0,0,0,0,0,"['hey', 'man', 'im', 'really', 'trying', 'edit...",...,22,1,5.590909,0,0,0.0,0,0,0,0
3,0001b41b1c6bb37e,more i cant make any real suggestions on impro...,0,0,0,0,0,0,0,"['cant', 'make', 'real', 'suggestion', 'improv...",...,49,1,6.530612,0,0,0.0,0,0,0,0
4,0001d958c54c6e35,you sir are my hero any chance you remember wh...,0,0,0,0,0,0,0,"['sir', 'hero', 'chance', 'remember', 'page', ...",...,6,1,5.000000,0,0,0.0,0,0,0,0

In [ ]:
print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 159571
Columns : 22

In [ ]:
df.isnull().sum()

id                    0
comment_text         26
toxic                 0
severe_toxic          0
obscene               0
threat                0
insult                0
identity_hate         0
label_count           0
tokens                0
clean_text           67
char_count            0
word_count            0
sentence_count        0
avg_word_length       0
stopword_count        0
punctuation_count     0
uppercase_ratio       0
digit_count           0
url_count             0
exclamation_count     0
question_count        0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 159504
Columns : 22

In [ ]:
df.isnull().sum()

id                   0
comment_text         0
toxic                0
severe_toxic         0
obscene              0
threat               0
insult               0
identity_hate        0
label_count          0
tokens               0
clean_text           0
char_count           0
word_count           0
sentence_count       0
avg_word_length      0
stopword_count       0
punctuation_count    0
uppercase_ratio      0
digit_count          0
url_count            0
exclamation_count    0
question_count       0
dtype: int64

In [ ]:
# Target Label Distribution
labels = [
    'toxic',
    'severe_toxic',
    'obscene',
    'threat',
    'insult',
    'identity_hate'
]

df[labels].sum().sort_values(ascending=False)

toxic            15294
obscene           8449
insult            7877
severe_toxic      1595
identity_hate     1405
threat             478
dtype: int64

In [ ]:
# Engineered Features Dataset
engineered_features = [
    'char_count',
    'word_count',
    'sentence_count',
    'avg_word_length',
    'stopword_count',
    'punctuation_count',
    'uppercase_ratio',
    'digit_count',
    'url_count',
    'exclamation_count',
    'question_count'
]

df[engineered_features].head()

,char_count,word_count,sentence_count,avg_word_length,stopword_count,punctuation_count,uppercase_ratio,digit_count,url_count,exclamation_count,question_count
0,171,26,1,5.615385,0,0,0.0,0,0,0,0
1,71,11,1,5.545455,0,0,0.0,0,0,0,0
2,144,22,1,5.590909,0,0,0.0,0,0,0,0
3,368,49,1,6.530612,0,0,0.0,0,0,0,0
4,35,6,1,5.000000,0,0,0.0,0,0,0,0

#**TF-IDF Feature Extraction**

It gives more importance to informative words while reducing the influence of common words.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# Build TF-IDF Features

tfidf = TfidfVectorizer(
    # max_features=10000,
    max_features=3000,
    min_df=5,
    max_df=0.90,
    ngram_range=(1,2)
)

X_tfidf = tfidf.fit_transform(df['clean_text'])

In [ ]:
# Shape
print(X_tfidf.shape)

(159504, 3000)

In [ ]:
# Top TF-IDF Features
feature_names = tfidf.get_feature_names_out()

print(feature_names[:100])

['ability' 'able' 'absolute' 'absolutely' 'absurd' 'abuse' 'abusing'
 'abusive' 'academic' 'accept' 'acceptable' 'accepted' 'accepted notable'
 'access' 'according' 'account' 'accuracy' 'accurate' 'accusation'
 'accuse' 'accused' 'accusing' 'acknowledge' 'across' 'act' 'acting'
 'action' 'active' 'activity' 'actor' 'actual' 'actually' 'ad' 'adam'
 'add' 'add information' 'add top' 'added' 'added article' 'added talk'
 'adding' 'adding note' 'adding top' 'addition' 'additional'
 'additionally' 'address' 'addressed' 'admin' 'administration'
 'administrative' 'administrator' 'admins' 'admit' 'adult' 'advance'
 'advertising' 'advice' 'advise' 'advocate' 'afd' 'affair' 'afraid'
 'africa' 'african' 'age' 'agenda' 'agent' 'ago' 'agree' 'agreed'
 'agreement' 'ah' 'ahead' 'aid' 'aim' 'aint' 'air' 'aircraft' 'aka' 'al'
 'albanian' 'album' 'allegation' 'alleged' 'allow' 'allowed' 'allows'
 'almost' 'alone' 'along' 'already' 'also' 'also please' 'altered'
 'alternative' 'although' 'always' 'amazing' 'america']

In [ ]:
# Function to Save file
import os
import joblib

def save_joblib(obj, file_path):
    # Delete existing file
    if os.path.exists(file_path):
        os.remove(file_path)
        print(f"Deleted: {file_path}")

    # Save new file
    joblib.dump(obj, file_path)
    print(f"Saved: {file_path}")

In [ ]:
# Save TF-IDF Model
import joblib

# joblib.dump( tfidf, "E:/PGDBA/BCG/Content/tfidf_vectorizer.pkl") # jupyter notebook
#save_joblib( tfidf, "/content/drive/MyDrive/Internship/AI_Content_Review/data/tfidf_vectorizer.pkl") # drive
save_joblib( tfidf,f"{PROJECT_DIR}/data/tfidf_vectorizer.pkl") # Manual upload
#(f"{PROJECT_DIR}/data/processed_train.csv")

Deleted: /content/AI_Content_Review/data/tfidf_vectorizer.pkl
Saved: /content/AI_Content_Review/data/tfidf_vectorizer.pkl

***Numerical Feature Scaling***

In [ ]:

# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()

# X_numeric = scaler.fit_transform(df[engineered_features])

# StandardScaler produces negative values, so switching to MinMaxScalar

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_numeric = scaler.fit_transform(df[engineered_features])

# Save Scaler

# joblib.dump( scaler, "E:/PGDBA/BCG/Content/scaler.pkl") # jupyter notebook
# save_joblib( scaler, "/content/drive/MyDrive/Internship/AI_Content_Review/data/scaler.pkl") # drive
save_joblib( scaler, f"{PROJECT_DIR}/data/scaler.pkl") # Manual upload

Deleted: /content/AI_Content_Review/data/scaler.pkl
Saved: /content/AI_Content_Review/data/scaler.pkl

***Combine TF-IDF + Numerical Features***

Traditional ML models often perform better when lexical TF-IDF features are augmented with engineered numerical features.

In [ ]:
from scipy.sparse import hstack

X_final = hstack([ X_tfidf, X_numeric])

print(X_final.shape)

(159504, 3011)

In [ ]:
X = X_final

In [ ]:
y = df[labels]

In [ ]:
!pip install iterative-stratification

Collecting iterative-stratification
  Downloading iterative_stratification-0.1.9-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (3.6.0)
Downloading iterative_stratification-0.1.9-py3-none-any.whl (8.5 kB)
Installing collected packages: iterative-stratification
Successfully installed iterative-stratification-0.1.9

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    multilabel_confusion_matrix,
    hamming_loss,
    jaccard_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

#**Train/Test Split**

***Multi-label Stratified Split***

In [ ]:
# # Multi-label Classification
# not using Binary Classification as there are multiple lables(Toxic, Severe Toxic, Threat, Offensive, Insult, Hate) not just Safe Vs Unsafe

msss = MultilabelStratifiedShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

# Convert COO → CSR
X = X.tocsr()

for train_idx, test_idx in msss.split(X_final, y):

    X_train = X[train_idx]
    X_test = X[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

In [ ]:
# Verify Split

print("="*60)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

print("="*60)

============================================================
Training Features : (127603, 3011)
Testing Features  : (31901, 3011)

Training Labels : (127603, 6)
Testing Labels  : (31901, 6)
============================================================

In [ ]:
# Save Prepared Data

#---------------------------------------local data(jupyter)---------------------------------------
# #joblib.dump( X_train, "E:/PGDBA/BCG/Content/X_train.pkl")
# #joblib.dump( X_test, "E:/PGDBA/BCG/Content/X_test.pkl")
# #joblib.dump( y_train, "E:/PGDBA/BCG/Content/y_train.pkl")
# #joblib.dump( y_test, "E:/PGDBA/BCG/Content/y_test.pkl")

#---------------------------------------Drive Data---------------------------------------
# save_joblib(X_train, "/content/drive/MyDrive/Internship/AI_Content_Review/data/X_train.pkl")
# save_joblib(X_train, "/content/drive/MyDrive/Internship/AI_Content_Review/data/X_test.pkl")
# save_joblib(X_train, "/content/drive/MyDrive/Internship/AI_Content_Review/data/y_train.pkl")
# save_joblib(X_train, "/content/drive/MyDrive/Internship/AI_Content_Review/data/y_test.pkl")

#---------------------------------------Manual uploaded Data---------------------------------------
joblib.dump( X_train, f"{PROJECT_DIR}/data/X_train.pkl")
joblib.dump( X_test, f"{PROJECT_DIR}/data/X_test.pkl")
joblib.dump( y_train, f"{PROJECT_DIR}/data/y_train.pkl")
joblib.dump( y_test, f"{PROJECT_DIR}/data/y_test.pkl")

['/content/AI_Content_Review/data/y_test.pkl']

***Key Insights***
1. Text has been transformed into structured numerical representations suitable for machine learning.
2. Engineered features such as word count and punctuation complement TF-IDF by capturing stylistic aspects of comments.
3. TF-IDF preserves the importance of informative terms while reducing the influence of very common words.
4. Combining lexical and numerical features provides a richer representation that can improve model performance for traditional classifiers.
5. The resulting feature matrix is ready for model training and evaluation.

#**Function to Save results to Excel**

In [ ]:
import os
import pandas as pd

# ==========================================================
# RESULT FILE LOCATION
# ==========================================================

RESULT_FOLDER = f"{PROJECT_DIR}/data"
RESULT_FILE = f"{PROJECT_DIR}/data/ModelComparison.csv"  #os.path.join(RESULT_FOLDER, "ModelComparison.csv")

os.makedirs(RESULT_FOLDER, exist_ok=True)

# ==========================================================
# FUNCTION TO SAVE / UPDATE RESULTS
# ==========================================================

def update_results_to_csv(metrics):

    # ------------------------------------------------------
    # First execution -> Create Excel automatically
    # ------------------------------------------------------

    if not os.path.exists(RESULT_FILE):

        model_results = pd.DataFrame([metrics])

    else:

        model_results = pd.read_csv(RESULT_FILE)

        # Remove previous result of the same model
        if "Model" in model_results.columns:
            model_results = model_results[
                model_results["Model"] != metrics["Model"]
            ]

        # Remove Rank column (it will be recreated)
        if "Rank" in model_results.columns:
            model_results = model_results.drop(columns=["Rank"])

        # Append new result
        model_results = pd.concat(
            [model_results, pd.DataFrame([metrics])],
            ignore_index=True
        )

    # ------------------------------------------------------
    # Sort by performance
    # ------------------------------------------------------

    model_results = model_results.sort_values(
        by=["Micro F1", "Macro F1", "Accuracy"],
        ascending=[False, False, False]
    ).reset_index(drop=True)

    # ------------------------------------------------------
    # Create Rank
    # ------------------------------------------------------

    model_results.insert(0, "Rank", range(1, len(model_results) + 1))

    # Move Rank column to first position
    cols = ["Rank"] + [
        c for c in model_results.columns
        if c != "Rank"
    ]

    model_results = model_results[cols]

    # ------------------------------------------------------
    # Round numeric values
    # ------------------------------------------------------

    numeric_cols = model_results.select_dtypes(
        include="number"
    ).columns

    model_results[numeric_cols] = (
        model_results[numeric_cols]
        .round(4)
    )

    # ------------------------------------------------------
    # Save Excel
    # ------------------------------------------------------

    model_results.to_csv(RESULT_FILE, index=False)

    print("=" * 60)
    print(f"{metrics['Model']} results saved successfully.")
    print(f"Results File : {RESULT_FILE}")
    print("=" * 60)

    return model_results

#**Evaluation Function**

In [ ]:
results = []

def evaluate_model(
    model_name,
    y_true,
    y_pred,
    y_prob=None
):

    metrics = {

        "Model":model_name,

        "Accuracy":
        accuracy_score(y_true,y_pred),

        "Micro Precision":
        precision_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Micro Recall":
        recall_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Micro F1":
        f1_score(
            y_true,
            y_pred,
            average='micro',
            zero_division=0
        ),

        "Macro F1":
        f1_score(
            y_true,
            y_pred,
            average='macro',
            zero_division=0
        ),

        "Weighted F1":
        f1_score(
            y_true,
            y_pred,
            average='weighted',
            zero_division=0
        ),

        "Hamming Loss":
        hamming_loss(
            y_true,
            y_pred
        ),

        "Jaccard Score":
        jaccard_score(
            y_true,
            y_pred,
            average='samples',
            zero_division=0
        )
    }

    if y_prob is not None:
        metrics["ROC-AUC"] = roc_auc_score(
            y_true,
            y_prob,
            average="micro"
        )
    else:
        metrics["ROC-AUC"] = np.nan

    results.append(metrics)

    update_results_to_csv(metrics)

    print("="*70)
    print(model_name)
    print("="*70)

    for k,v in metrics.items():

        if k!="Model":

            print(f"{k:<20}: {v:.4f}")

#**Model 6 - BERT**

In [ ]:
# Step 1: Install Required Libraries

!pip install -q transformers
!pip install -q accelerate
!pip install -q datasets
!pip install -q evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.9 MB/s eta 0:00:00

In [ ]:
# Step 2: Import Libraries

import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from transformers import (
    BertConfig,
    BertTokenizerFast,
    BertForSequenceClassification,
    get_linear_schedule_with_warmup
)

from torch.optim import AdamW
from torch.cuda.amp import autocast, GradScaler
import copy
import time

# from transformers import (
#     BertConfig,
#     BertTokenizerFast,
#     BertForSequenceClassification,
#     get_linear_schedule_with_warmup
# )

from torch.optim import AdamW
from tqdm.auto import tqdm

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    hamming_loss,
    jaccard_score,
    roc_auc_score,
    classification_report
)

In [ ]:
# Step 3: Device Configuration

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

# if the output is cpu # in Google Colab, then GPU is not enabled for your notebook.
# BERT training on CPU will be very slow (several hours on the Jigsaw dataset), so it's worth enabling GPU before proceeding.

cuda

In [ ]:
# Enabling GPU

#Go to Runtime(toolbar) → Change runtime type → Set: Hardware accelerator: GPU → Click Save.


print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

In [ ]:
X_train = df.iloc[train_idx]["clean_text"].tolist()
X_test = df.iloc[test_idx]["clean_text"].tolist()

y_train = df.iloc[train_idx][labels].values
y_test = df.iloc[test_idx][labels].values

In [ ]:
import transformers
print(transformers.__version__)

5.13.1

In [ ]:
# Step 5: Load BERT Tokenizer
tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased", force_download=True)

tokenizer.save_pretrained(f"{PROJECT_DIR}/models/bert")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

('/content/AI_Content_Review/models/bert/tokenizer_config.json',
 '/content/AI_Content_Review/models/bert/tokenizer.json')

In [ ]:
import json

with open(f"{PROJECT_DIR}/models/bert/special_tokens_map.json", "w") as f:
    json.dump(tokenizer.special_tokens_map, f, indent=4)

In [ ]:
vocab = tokenizer.get_vocab()

# Sort by token ID
vocab = sorted(vocab.items(), key=lambda x: x[1])

with open(f"{PROJECT_DIR}/models/bert/vocab.txt", "w", encoding="utf-8") as f:
    for token, _ in vocab:
        f.write(token + "\n")

In [ ]:
# Step 6: Tokenize Text
MAX_LENGTH = 128 #64

train_encodings = tokenizer(
    X_train,
    truncation=True,
    padding=True,
    max_length=MAX_LENGTH
)

test_encodings = tokenizer(
    X_test,
    truncation=True,
    padding=True,
    max_length=MAX_LENGTH
)

In [ ]:
# Step 7: Create Dataset Class
class ToxicDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(value[idx])
            for key, value in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx],
            dtype=torch.float
        )

        return item

In [ ]:
# Step 8: Create DataLoaders
train_dataset = ToxicDataset(
    train_encodings,
    y_train
)

test_dataset = ToxicDataset(
    test_encodings,
    y_test
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

# learning rate, batch size other hyper parameters to be included

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

In [ ]:
# ============================================================
# STEP 9 : LOAD BERT MODEL (OPTIMIZED)
# ============================================================


# ============================================================
# BERT CONFIGURATION
# ============================================================

config = BertConfig.from_pretrained(
    "bert-base-uncased",
    num_labels=6,
    problem_type="multi_label_classification",
    hidden_dropout_prob=0.3,
    attention_probs_dropout_prob=0.3
)

bertModel = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    config=config
)

bertModel.to(device)

print("Model Loaded Successfully")
print(f"Running on : {device}")

# ============================================================
# FREEZE LOWER BERT LAYERS
# ============================================================

freeze_layers = 8

for layer in bertModel.bert.encoder.layer[:freeze_layers]:
    for param in layer.parameters():
        param.requires_grad = False

print(f"First {freeze_layers} encoder layers frozen.")

# ============================================================
# TRAINABLE PARAMETERS
# ============================================================

trainable_params = sum(
    p.numel()
    for p in bertModel.parameters()
    if p.requires_grad
)

total_params = sum(
    p.numel()
    for p in bertModel.parameters()
)

print(f"Trainable Parameters : {trainable_params:,}")
print(f"Total Parameters     : {total_params:,}")

# ============================================================
# HYPERPARAMETERS
# ============================================================

EPOCHS = 3

LEARNING_RATE = 2e-5

WEIGHT_DECAY = 0.01

MAX_GRAD_NORM = 1.0

EARLY_STOPPING_PATIENCE = 2

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = AdamW(
    bertModel.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)

# ============================================================
# LEARNING RATE SCHEDULER
# ============================================================

total_steps = len(train_loader) * EPOCHS

warmup_steps = int(0.1 * total_steps)

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps
)

print(f"Training Batches : {len(train_loader)}")
print(f"Validation Batches : {len(test_loader)}")
print(f"Total Steps : {total_steps}")
print(f"Warmup Steps : {warmup_steps}")

# ============================================================
# MIXED PRECISION (FP16)
# ============================================================

scaler = GradScaler()

print("Mixed Precision Enabled")

# ============================================================
# EARLY STOPPING VARIABLES
# ============================================================

val_loss = float("inf")

epochs_without_improvement = 0

history = {
    "train_loss": [],
    "val_loss": []
}

# ============================================================
# STORE MODEL WEIGHTS
# ============================================================

model_weights = copy.deepcopy(
    bertModel.state_dict()
)

# ============================================================
# GPU INFORMATION
# ============================================================

if torch.cuda.is_available():

    print("=" * 60)
    print("GPU INFORMATION")
    print("=" * 60)

    print("GPU :", torch.cuda.get_device_name(0))

    print(
        "Allocated Memory :",
        round(torch.cuda.memory_allocated(0) / 1024**3, 2),
        "GB"
    )

    print(
        "Cached Memory :",
        round(torch.cuda.memory_reserved(0) / 1024**3, 2),
        "GB"
    )

print("=" * 60)
print("BERT INITIALIZATION COMPLETED")
print("=" * 60)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded Successfully
Running on : cuda
First 8 encoder layers frozen.
Trainable Parameters : 52,783,878
Total Parameters     : 109,486,854
Training Batches : 1994
Validation Batches : 499
Total Steps : 5982
Warmup Steps : 598
Mixed Precision Enabled
============================================================
GPU INFORMATION
============================================================
GPU : Tesla T4
Allocated Memory : 0.82 GB
Cached Memory : 0.9 GB
============================================================
BERT INITIALIZATION COMPLETED
============================================================

In [ ]:
# ============================================================
# TRAINING LOOP
# ============================================================

print("=" * 70)
print("Starting BERT Training...")
print("=" * 70)

start_time = time.time()

for epoch in range(EPOCHS):

    print(f"\nEpoch {epoch+1}/{EPOCHS}")
    print("-" * 70)

    ###########################################################
    # TRAINING
    ###########################################################

    bertModel.train()

    train_loss = 0

    progress_bar = tqdm(
        train_loader,
        desc=f"Training Epoch {epoch+1}",
        leave=True
    )

    for batch in progress_bar:

        input_ids = batch["input_ids"].to(device, non_blocking=True)
        attention_mask = batch["attention_mask"].to(device, non_blocking=True)
        labels = batch["labels"].float().to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        # Mixed Precision Forward Pass
        with autocast():

            outputs = bertModel(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            loss = outputs.loss

        train_loss += loss.item()

        # Backpropagation
        scaler.scale(loss).backward()

        # Gradient Clipping
        scaler.unscale_(optimizer)

        torch.nn.utils.clip_grad_norm_(
            bertModel.parameters(),
            MAX_GRAD_NORM
        )

        scaler.step(optimizer)

        scaler.update()

        scheduler.step()

        progress_bar.set_postfix(
            Loss=f"{loss.item():.4f}",
            LR=f"{scheduler.get_last_lr()[0]:.2e}"
        )

    ###########################################################
    # TRAINING LOSS
    ###########################################################

    avg_train_loss = train_loss / len(train_loader)

    ###########################################################
    # VALIDATION
    ###########################################################

    bertModel.eval()

    validation_loss = 0

    with torch.no_grad():

        for batch in tqdm(
            test_loader,
            desc="Validation",
            leave=False
        ):

            input_ids = batch["input_ids"].to(device, non_blocking=True)

            attention_mask = batch["attention_mask"].to(device, non_blocking=True)

            labels = batch["labels"].float().to(device, non_blocking=True)

            with autocast():

                outputs = bertModel(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    labels=labels
                )

                loss = outputs.loss

            validation_loss += loss.item()

    avg_val_loss = validation_loss / len(test_loader)

    ###########################################################
    # STORE HISTORY
    ###########################################################

    history["train_loss"].append(avg_train_loss)
    history["val_loss"].append(avg_val_loss)

    ###########################################################
    # PRINT METRICS
    ###########################################################

    print(f"\nTraining Loss   : {avg_train_loss:.4f}")
    print(f"Validation Loss : {avg_val_loss:.4f}")

    ###########################################################
    # SAVE MODEL
    ###########################################################

    if avg_val_loss < val_loss:

        print("Validation improved.")
        print("Saving Model...")

        val_loss = avg_val_loss

        epochs_without_improvement = 0

        model_weights = copy.deepcopy(
            bertModel.state_dict()
        )

        torch.save(model_weights,f"{PROJECT_DIR}/models/bert_model.pt")

        bertModel.save_pretrained(f"{PROJECT_DIR}/models/bert")

        tokenizer.save_pretrained(f"{PROJECT_DIR}/models/bert")

    else:

        epochs_without_improvement += 1

        print(
            f"No Improvement "
            f"({epochs_without_improvement}/{EARLY_STOPPING_PATIENCE})"
        )

    ###########################################################
    # EARLY STOPPING
    ###########################################################

    if epochs_without_improvement >= EARLY_STOPPING_PATIENCE:

        print("\nEarly Stopping Triggered.")

        break

###############################################################
# TRAINING COMPLETE
###############################################################

training_time = time.time() - start_time

print("=" * 70)
print("Training Completed")
print("=" * 70)

print(f"Validation Loss : {val_loss:.4f}")

print(
    f"Training Time : "
    f"{training_time/60:.2f} minutes"
)

###############################################################
# LOAD MODEL
###############################################################

bertModel.load_state_dict(model_weights)

bertModel.eval()

print("\BERT Model Loaded Successfully.")

======================================================================
Starting BERT Training...
======================================================================

Epoch 1/3
----------------------------------------------------------------------

Training Epoch 1:   0%|          | 0/1994 [00:00<?, ?it/s]

Validation:   0%|          | 0/499 [00:00<?, ?it/s]

Training Loss   : 0.1135
Validation Loss : 0.0637
Validation improved.
Saving Model...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 2/3
----------------------------------------------------------------------

Training Epoch 2:   0%|          | 0/1994 [00:00<?, ?it/s]

Validation:   0%|          | 0/499 [00:00<?, ?it/s]

Training Loss   : 0.0543
Validation Loss : 0.0505
Validation improved.
Saving Model...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 3/3
----------------------------------------------------------------------

Training Epoch 3:   0%|          | 0/1994 [00:00<?, ?it/s]

In [ ]:
# ============================================================
# LOAD MODEL FOR EVALUATION
# ============================================================

print("="*70)
print("Loading BERT Model")
print("="*70)

bertModel = BertForSequenceClassification.from_pretrained(f"{PROJECT_DIR}/models/bert")

bertModel.to(device)
bertModel.eval()

print("Model loaded successfully.")

# ============================================================
# PREDICTION
# ============================================================

all_labels = []
all_predictions = []
all_probabilities = []

prediction_start = time.time()

with torch.no_grad():

    progress_bar = tqdm(
        test_loader,
        desc="Predicting"
    )

    for batch in progress_bar:

        input_ids = batch["input_ids"].to(device, non_blocking=True)

        attention_mask = batch["attention_mask"].to(
            device,
            non_blocking=True
        )

        labels = batch["labels"].to(device)

        with autocast():

            outputs = bertModel(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            logits = outputs.logits

        probabilities = torch.sigmoid(logits)

        predictions = (probabilities >= 0.50).int()

        all_probabilities.extend(
            probabilities.cpu().numpy()
        )

        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

prediction_time = time.time() - prediction_start

print(f"\nPrediction Time : {prediction_time:.2f} seconds")

# ============================================================
# CONVERT TO NUMPY
# ============================================================

y_true = np.array(all_labels)

y_pred = np.array(all_predictions)

y_prob = np.array(all_probabilities)

print("\nPrediction Shapes")

print("y_true :", y_true.shape)

print("y_pred :", y_pred.shape)

print("y_prob :", y_prob.shape)

# ============================================================
# MODEL EVALUATION
# ============================================================

print("="*70)
print("BERT MODEL PERFORMANCE")
print("="*70)

evaluate_model(

    model_name="BERT",

    y_true=y_true,

    y_pred=y_pred,

    y_prob=y_prob

)

In [ ]:
# ============================================================
# INDIVIDUAL CLASSIFICATION REPORT
# ============================================================

print("="*70)
print("Classification Report")
print("="*70)

labels = [
    'toxic',
    'severe_toxic',
    'obscene',
    'threat',
    'insult',
    'identity_hate'
]

print(

    classification_report(

        y_true,

        y_pred,

        target_names=labels,

        zero_division=0

    )

)

In [ ]:
# ============================================================
# SAVE FINAL MODEL
# ============================================================

print("="*70)
print("Saving Final Model")
print("="*70)

bertModel.save_pretrained(f"{PROJECT_DIR}/models/bert")

tokenizer.save_pretrained(f"{PROJECT_DIR}/models/bert")

print("Model Saved Successfully")

# ============================================================
# SAVE CONFIGURATION
# ============================================================

training_config = {

    "Model": "BERT",

    "Epochs": EPOCHS,

    "Batch Size": train_loader.batch_size,

    "Learning Rate": LEARNING_RATE,

    "Weight Decay": WEIGHT_DECAY,

    "Max Length": MAX_LENGTH,

    "Frozen Layers": freeze_layers,

    "Warmup Steps": warmup_steps,

    "Validation Loss": val_loss

}

config_df = pd.DataFrame(
    training_config.items(),
    columns=["Parameter", "Value"]
)

config_df.to_csv(f"{PROJECT_DIR}/models/bert/training_configuration.csv",

    index=False

)

print("Training Configuration Saved")

# ============================================================
# BERT PREDICTION FUNCTION
# ============================================================

def predict_toxicity(text):

    bertModel.eval()

    encoding = tokenizer(

        text,

        return_tensors="pt",

        truncation=True,

        padding=True,

        max_length=MAX_LENGTH

    )

    input_ids = encoding["input_ids"].to(device)

    attention_mask = encoding["attention_mask"].to(device)

    with torch.no_grad():

        outputs = bertModel(

            input_ids=input_ids,

            attention_mask=attention_mask

        )

        probabilities = torch.sigmoid(

            outputs.logits

        ).cpu().numpy()[0]

    prediction = (

        probabilities >= 0.50

    ).astype(int)

    result = {

        label: {

            "Prediction": int(pred),

            "Probability": round(float(prob),4)

        }

        for label, pred, prob in zip(

            labels,

            prediction,

            probabilities

        )

    }

    return result

print("="*70)
print("BERT PIPELINE COMPLETED SUCCESSFULLY")
print("="*70)